// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdxirshxxjkzqmamcmlr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkeGlyc2h4eGprenFtYW1jbWxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxOTc0MTIsImV4cCI6MjA2Mjc3MzQxMn0.l-xnmSosykOQWdmP8IUa4KVYUu94kRu14AA51hYyj08";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);